#include "internal_dataref_list.h"

#include <boost/algorithm/string/classification.hpp>
#include <boost/algorithm/string/split.hpp>

// To generate this list: 
// cd X-Plane 11/Output/preferences
// grep private drt_last_run_datarefs.txt > datarefs_keep.txt
// grep iphone drt_last_run_datarefs.txt >> datarefs_keep.txt
//
// This was done on mac. I couldn't get the list consistently on windows.

const char * raw_list = R"""(
sim/private/controls/acf/debug/reload_config
sim/private/controls/ag/agb_hilite_bad_fit
sim/private/controls/ag/agb_warnings
sim/private/controls/ag/ann_shrub_density
sim/private/controls/ag/ann_shrub_lod
sim/private/controls/ag/ann_tree_density1
sim/private/controls/ag/ann_tree_density2
sim/private/controls/ag/ann_tree_lod1
sim/private/controls/ag/ann_tree_lod2
sim/private/controls/ag/block/slope_sample_dist
sim/private/controls/ag/block/slope_sample_max
sim/private/controls/ag/default_tile_lod
sim/private/controls/ag/fill_shrub_density
sim/private/controls/ag/fill_shrub_lod
sim/private/controls/ag/fill_tree_density1
sim/private/controls/ag/fill_tree_density2
sim/private/controls/ag/fill_tree_lod1
sim/private/controls/ag/fill_tree_lod2
sim/private/controls/ag/inflate_dist_min
sim/private/controls/ag/show_dsf_poly
sim/private/controls/ag/shrub_height
sim/private/controls/ag/tile_lod_bias
sim/private/controls/ag/tree_height_jitter
sim/private/controls/ag/tree_rotation_jitter
sim/private/controls/agb/debug_spelling_gaps
sim/private/controls/ai/debug/brake_hard
sim/private/controls/ai/debug/rate_landings
sim/private/controls/ai/debug/rate_takeoffs
sim/private/controls/airp/debug_ramp_starts
sim/private/controls/airport/max_error
sim/private/controls/airport/max_tight_curve
sim/private/controls/airport/min_error
sim/private/controls/airport/min_tight_curve
sim/private/controls/airport/recurse_depth
sim/private/controls/airport/taxi_straight_line_split
sim/private/controls/atc/arrival_spacing_seconds
sim/private/controls/atc/debug/acfCmds
sim/private/controls/atc/debug/airspace
sim/private/controls/atc/debug/ai_one_per_frame
sim/private/controls/atc/debug/dijkstra/log
sim/private/controls/atc/debug/dijkstra/show_node_cost
sim/private/controls/atc/debug/log_spawn
sim/private/controls/atc/debug/network
sim/private/controls/atc/debug/print_q
sim/private/controls/atc/debug/reload_atc_voices
sim/private/controls/atc/debug/routing
sim/private/controls/atc/debug/rwy_flow
sim/private/controls/atc/debug/rwy_selection
sim/private/controls/atc/debug/show_ai_metrics
sim/private/controls/atc/debug/taxi
sim/private/controls/atc/debug/taxi/debug_to_gate
sim/private/controls/atc/debug/taxi/debug_to_runway
sim/private/controls/atc/debug/taxi/departure
sim/private/controls/atc/debug/test_taxi_width
sim/private/controls/atc/debug/vectors
sim/private/controls/atc/debug/vector_tee
sim/private/controls/atc/debug/vector_w1
sim/private/controls/atc/debug/vector_w2
sim/private/controls/atc/debug/vector_w3
sim/private/controls/atc/default/hot_zone_length
sim/private/controls/atc/default/hot_zone_width
sim/private/controls/atc/record_ai_crumbs
sim/private/controls/atc/routing/min_seg_len_for_steep_penalty
sim/private/controls/atc/routing/runway_active_oppdir_fee
sim/private/controls/atc/routing/runway_active_samedir_fee
sim/private/controls/atc/routing/runway_inactive_samedir_fee
sim/private/controls/atc/routing/runway_ldg_oppdir_weight
sim/private/controls/atc/routing/runway_ldg_samedir_weight
sim/private/controls/atc/routing/runway_mult_shallow_max
sim/private/controls/atc/routing/runway_mult_shallow_min
sim/private/controls/atc/routing/runway_mult_steep_max
sim/private/controls/atc/routing/runway_mult_steep_min
sim/private/controls/atc/routing/runway_steep_angle
sim/private/controls/atc/routing/taxiway_mult_shallow_max
sim/private/controls/atc/routing/taxiway_mult_shallow_min
sim/private/controls/atc/routing/taxiway_mult_steep_max
sim/private/controls/atc/routing/taxiway_mult_steep_min
sim/private/controls/atc/routing/taxiway_oppdir_weight
sim/private/controls/atc/routing/taxiway_samedir_weight
sim/private/controls/atc/routing/taxiway_steep_angle
sim/private/controls/atc/routing/taxiway_too_small_weight
sim/private/controls/atc/timing/takeoff/cross/hold_short
sim/private/controls/atc/timing/takeoff/cross/lined_up
sim/private/controls/atc/timing/takeoff/ors/lined_up
sim/private/controls/atc/timing/takeoff/src/hold_short
sim/private/controls/atc/timing/takeoff/srs/hold_short
sim/private/controls/atc/timing/takeoff/srs/lined_up
sim/private/controls/atc/txon/nag_timer_sec
sim/private/controls/atmo/atmo_scale_raleigh
sim/private/controls/atmo/inscatter_gain_mie
sim/private/controls/atmo/inscatter_gain_raleigh
sim/private/controls/atmo/scatter_raleigh_b
sim/private/controls/atmo/scatter_raleigh_g
sim/private/controls/atmo/scatter_raleigh_r
sim/private/controls/autogen/ags_corner
sim/private/controls/autogen/ags_slop_h
sim/private/controls/autogen/ags_slop_v
sim/private/controls/autogen/use_atomic_corners
sim/private/controls/beaches/kill_beaches
sim/private/controls/beaches/max_batch
sim/private/controls/blur/max_kernel
sim/private/controls/camera/kill_wheel_zoom
sim/private/controls/caps/use_3dwater
sim/private/controls/caps/use_csm
sim/private/controls/caps/use_HDR
sim/private/controls/caps/use_multilayer_fog
sim/private/controls/caps/use_reflective_water
sim/private/controls/cars/density_factor
sim/private/controls/cars/lod_hdr
sim/private/controls/cars/lod_min
sim/private/controls/cars/min_cull
sim/private/controls/cars/show_spawn
sim/private/controls/cloud/bright_bottom
sim/private/controls/cloud/fade_far_end
sim/private/controls/cloud/fade_far_start
sim/private/controls/cloud/fade_near_end
sim/private/controls/cloud/fade_near_start
sim/private/controls/cloud/offscreen_res_tight
sim/private/controls/cloud/offscreen_scale
sim/private/controls/cloud/offscreen_tight
sim/private/controls/cloud/offscreen_tweak
sim/private/controls/cloud/sample_extra_top
sim/private/controls/cloud/sample_opacity
sim/private/controls/cloud/sample_radius
sim/private/controls/cloud/use_offscreen
sim/private/controls/cloud/water_line_base
sim/private/controls/cloud/water_line_tops
sim/private/controls/clouds/2d_fade_in_end
sim/private/controls/clouds/2d_fade_in_start
sim/private/controls/clouds/2d_fade_out_end
sim/private/controls/clouds/2d_fade_out_start
sim/private/controls/clouds/ambient_gain
sim/private/controls/clouds/bias_const
sim/private/controls/clouds/bias_slope
sim/private/controls/clouds/bkn/alpha_layer_0
sim/private/controls/clouds/bkn/alpha_layer_1
sim/private/controls/clouds/bkn/alpha_layer_2
sim/private/controls/clouds/bkn/alpha_layer_3
sim/private/controls/clouds/bkn/alpha_layer_4
sim/private/controls/clouds/bkn/alpha_layer_5
sim/private/controls/clouds/bkn/bot
sim/private/controls/clouds/bkn/flat_res
sim/private/controls/clouds/bkn/squish_layer_0
sim/private/controls/clouds/bkn/squish_layer_1
sim/private/controls/clouds/bkn/squish_layer_2
sim/private/controls/clouds/bkn/squish_layer_3
sim/private/controls/clouds/bkn/squish_layer_4
sim/private/controls/clouds/bkn/squish_layer_5
sim/private/controls/clouds/bkn/top
sim/private/controls/clouds/cell_radius/0/0,0
sim/private/controls/clouds/cell_radius/0/0,1
sim/private/controls/clouds/cell_radius/0/0,2
sim/private/controls/clouds/cell_radius/0/0,3
sim/private/controls/clouds/cell_radius/0/1,0
sim/private/controls/clouds/cell_radius/0/1,1
sim/private/controls/clouds/cell_radius/0/1,2
sim/private/controls/clouds/cell_radius/0/1,3
sim/private/controls/clouds/cell_radius/0/2,0
sim/private/controls/clouds/cell_radius/0/2,1
sim/private/controls/clouds/cell_radius/0/2,2
sim/private/controls/clouds/cell_radius/0/2,3
sim/private/controls/clouds/cell_radius/0/3,0
sim/private/controls/clouds/cell_radius/0/3,1
sim/private/controls/clouds/cell_radius/0/3,2
sim/private/controls/clouds/cell_radius/0/3,3
sim/private/controls/clouds/cell_radius/1/0,0
sim/private/controls/clouds/cell_radius/1/0,1
sim/private/controls/clouds/cell_radius/1/0,2
sim/private/controls/clouds/cell_radius/1/0,3
sim/private/controls/clouds/cell_radius/1/1,0
sim/private/controls/clouds/cell_radius/1/1,1
sim/private/controls/clouds/cell_radius/1/1,2
sim/private/controls/clouds/cell_radius/1/1,3
sim/private/controls/clouds/cell_radius/1/2,0
sim/private/controls/clouds/cell_radius/1/2,1
sim/private/controls/clouds/cell_radius/1/2,2
sim/private/controls/clouds/cell_radius/1/2,3
sim/private/controls/clouds/cell_radius/1/3,0
sim/private/controls/clouds/cell_radius/1/3,1
sim/private/controls/clouds/cell_radius/1/3,2
sim/private/controls/clouds/cell_radius/1/3,3
sim/private/controls/clouds/cell_radius/2/0,0
sim/private/controls/clouds/cell_radius/2/0,1
sim/private/controls/clouds/cell_radius/2/0,2
sim/private/controls/clouds/cell_radius/2/0,3
sim/private/controls/clouds/cell_radius/2/1,0
sim/private/controls/clouds/cell_radius/2/1,1
sim/private/controls/clouds/cell_radius/2/1,2
sim/private/controls/clouds/cell_radius/2/1,3
sim/private/controls/clouds/cell_radius/2/2,0
sim/private/controls/clouds/cell_radius/2/2,1
sim/private/controls/clouds/cell_radius/2/2,2
sim/private/controls/clouds/cell_radius/2/2,3
sim/private/controls/clouds/cell_radius/2/3,0
sim/private/controls/clouds/cell_radius/2/3,1
sim/private/controls/clouds/cell_radius/2/3,2
sim/private/controls/clouds/cell_radius/2/3,3
sim/private/controls/clouds/cell_radius/3/0,0
sim/private/controls/clouds/cell_radius/3/0,1
sim/private/controls/clouds/cell_radius/3/0,2
sim/private/controls/clouds/cell_radius/3/0,3
sim/private/controls/clouds/cell_radius/3/1,0
sim/private/controls/clouds/cell_radius/3/1,1
sim/private/controls/clouds/cell_radius/3/1,2
sim/private/controls/clouds/cell_radius/3/1,3
sim/private/controls/clouds/cell_radius/3/2,0
sim/private/controls/clouds/cell_radius/3/2,1
sim/private/controls/clouds/cell_radius/3/2,2
sim/private/controls/clouds/cell_radius/3/2,3
sim/private/controls/clouds/cell_radius/3/3,0
sim/private/controls/clouds/cell_radius/3/3,1
sim/private/controls/clouds/cell_radius/3/3,2
sim/private/controls/clouds/cell_radius/3/3,3
sim/private/controls/clouds/cell_radius/4/0,0
sim/private/controls/clouds/cell_radius/4/0,1
sim/private/controls/clouds/cell_radius/4/0,2
sim/private/controls/clouds/cell_radius/4/0,3
sim/private/controls/clouds/cell_radius/4/1,0
sim/private/controls/clouds/cell_radius/4/1,1
sim/private/controls/clouds/cell_radius/4/1,2
sim/private/controls/clouds/cell_radius/4/1,3
sim/private/controls/clouds/cell_radius/4/2,0
sim/private/controls/clouds/cell_radius/4/2,1
sim/private/controls/clouds/cell_radius/4/2,2
sim/private/controls/clouds/cell_radius/4/2,3
sim/private/controls/clouds/cell_radius/4/3,0
sim/private/controls/clouds/cell_radius/4/3,1
sim/private/controls/clouds/cell_radius/4/3,2
sim/private/controls/clouds/cell_radius/4/3,3
sim/private/controls/clouds/cell_radius/5/0,0
sim/private/controls/clouds/cell_radius/5/0,1
sim/private/controls/clouds/cell_radius/5/0,2
sim/private/controls/clouds/cell_radius/5/0,3
sim/private/controls/clouds/cell_radius/5/1,0
sim/private/controls/clouds/cell_radius/5/1,1
sim/private/controls/clouds/cell_radius/5/1,2
sim/private/controls/clouds/cell_radius/5/1,3
sim/private/controls/clouds/cell_radius/5/2,0
sim/private/controls/clouds/cell_radius/5/2,1
sim/private/controls/clouds/cell_radius/5/2,2
sim/private/controls/clouds/cell_radius/5/2,3
sim/private/controls/clouds/cell_radius/5/3,0
sim/private/controls/clouds/cell_radius/5/3,1
sim/private/controls/clouds/cell_radius/5/3,2
sim/private/controls/clouds/cell_radius/5/3,3
sim/private/controls/clouds/check_z_hdr
sim/private/controls/clouds/cloud_shadow_lighten_ratio
sim/private/controls/clouds/count_ratio/0
sim/private/controls/clouds/count_ratio/1
sim/private/controls/clouds/count_ratio/2
sim/private/controls/clouds/count_ratio/3
sim/private/controls/clouds/count_ratio/4
sim/private/controls/clouds/count_ratio/5
sim/private/controls/clouds/debug_color_layers
sim/private/controls/clouds/debug_color_offscreen
sim/private/controls/clouds/debug_mask
sim/private/controls/clouds/debug_mode
sim/private/controls/clouds/diffuse_gain
sim/private/controls/clouds/first_res_3d
sim/private/controls/clouds/flat_res
sim/private/controls/clouds/hi_cir/alpha_layer_0
sim/private/controls/clouds/hi_cir/alpha_layer_1
sim/private/controls/clouds/hi_cir/alpha_layer_2
sim/private/controls/clouds/hi_cir/alpha_layer_3
sim/private/controls/clouds/hi_cir/alpha_layer_4
sim/private/controls/clouds/hi_cir/alpha_layer_5
sim/private/controls/clouds/hi_cir/bot
sim/private/controls/clouds/hi_cir/flat_res
sim/private/controls/clouds/hi_cir/squish_layer_0
sim/private/controls/clouds/hi_cir/squish_layer_1
sim/private/controls/clouds/hi_cir/squish_layer_2
sim/private/controls/clouds/hi_cir/squish_layer_3
sim/private/controls/clouds/hi_cir/squish_layer_4
sim/private/controls/clouds/hi_cir/squish_layer_5
sim/private/controls/clouds/hi_cir/top
sim/private/controls/clouds/image_size_x
sim/private/controls/clouds/image_size_y
sim/private/controls/clouds/kill_2d
sim/private/controls/clouds/kill_3d
sim/private/controls/clouds/kill_blanket
sim/private/controls/clouds/kill_offscreen_blit
sim/private/controls/clouds/kill_onscreen_render
sim/private/controls/clouds/last_res_3d
sim/private/controls/clouds/light_curve_power
sim/private/controls/clouds/light_curve_ratio
sim/private/controls/clouds/limit_far
sim/private/controls/clouds/lo_cir/alpha_layer_0
sim/private/controls/clouds/lo_cir/alpha_layer_1
sim/private/controls/clouds/lo_cir/alpha_layer_2
sim/private/controls/clouds/lo_cir/alpha_layer_3
sim/private/controls/clouds/lo_cir/alpha_layer_4
sim/private/controls/clouds/lo_cir/alpha_layer_5
sim/private/controls/clouds/lo_cir/bot
sim/private/controls/clouds/lo_cir/flat_res
sim/private/controls/clouds/lo_cir/squish_layer_0
sim/private/controls/clouds/lo_cir/squish_layer_1
sim/private/controls/clouds/lo_cir/squish_layer_2
sim/private/controls/clouds/lo_cir/squish_layer_3
sim/private/controls/clouds/lo_cir/squish_layer_4
sim/private/controls/clouds/lo_cir/squish_layer_5
sim/private/controls/clouds/lo_cir/top
sim/private/controls/clouds/min_res_for_shadow
sim/private/controls/clouds/ovc/alpha_layer_0
sim/private/controls/clouds/ovc/alpha_layer_1
sim/private/controls/clouds/ovc/alpha_layer_2
sim/private/controls/clouds/ovc/alpha_layer_3
sim/private/controls/clouds/ovc/alpha_layer_4
sim/private/controls/clouds/ovc/alpha_layer_5
sim/private/controls/clouds/ovc/bot
sim/private/controls/clouds/ovc/flat_res
sim/private/controls/clouds/ovc/squish_layer_0
sim/private/controls/clouds/ovc/squish_layer_1
sim/private/controls/clouds/ovc/squish_layer_2
sim/private/controls/clouds/ovc/squish_layer_3
sim/private/controls/clouds/ovc/squish_layer_4
sim/private/controls/clouds/ovc/squish_layer_5
sim/private/controls/clouds/ovc/top
sim/private/controls/clouds/overdraw_control
sim/private/controls/clouds/plot_radius
sim/private/controls/clouds/radius_for_2d
sim/private/controls/clouds/sct/alpha_layer_0
sim/private/controls/clouds/sct/alpha_layer_1
sim/private/controls/clouds/sct/alpha_layer_2
sim/private/controls/clouds/sct/alpha_layer_3
sim/private/controls/clouds/sct/alpha_layer_4
sim/private/controls/clouds/sct/alpha_layer_5
sim/private/controls/clouds/sct/bot
sim/private/controls/clouds/sct/flat_res
sim/private/controls/clouds/sct/squish_layer_0
sim/private/controls/clouds/sct/squish_layer_1
sim/private/controls/clouds/sct/squish_layer_2
sim/private/controls/clouds/sct/squish_layer_3
sim/private/controls/clouds/sct/squish_layer_4
sim/private/controls/clouds/sct/squish_layer_5
sim/private/controls/clouds/sct/top
sim/private/controls/clouds/shadow_size
sim/private/controls/clouds/shad_alpha_dry
sim/private/controls/clouds/shad_alpha_wet
sim/private/controls/clouds/shad_radius
sim/private/controls/clouds/size_control/0
sim/private/controls/clouds/size_control/1
sim/private/controls/clouds/size_control/2
sim/private/controls/clouds/size_control/3
sim/private/controls/clouds/size_control/4
sim/private/controls/clouds/size_control/5
sim/private/controls/clouds/skip_draw
sim/private/controls/clouds/skip_map
sim/private/controls/clouds/skip_write
sim/private/controls/clouds/soft_occlude
sim/private/controls/clouds/spec_gain
sim/private/controls/clouds/str/alpha_layer_0
sim/private/controls/clouds/str/alpha_layer_1
sim/private/controls/clouds/str/alpha_layer_2
sim/private/controls/clouds/str/alpha_layer_3
sim/private/controls/clouds/str/alpha_layer_4
sim/private/controls/clouds/str/alpha_layer_5
sim/private/controls/clouds/str/bot
sim/private/controls/clouds/str/flat_res
sim/private/controls/clouds/str/squish_layer_0
sim/private/controls/clouds/str/squish_layer_1
sim/private/controls/clouds/str/squish_layer_2
sim/private/controls/clouds/str/squish_layer_3
sim/private/controls/clouds/str/squish_layer_4
sim/private/controls/clouds/str/squish_layer_5
sim/private/controls/clouds/str/top
sim/private/controls/cockpit/allow_solid_wall_testing
sim/private/controls/cockpit/far_clip_ratio
sim/private/controls/cockpit/minimum_agl
sim/private/controls/cockpit/near_clip_ratio
sim/private/controls/cockpit/wall_hit_extra
sim/private/controls/collector/kill_hw
sim/private/controls/collector/kill_imm
sim/private/controls/collector/kill_slow
sim/private/controls/collector/max_imm
sim/private/controls/cube/kill_all
sim/private/controls/cube/kill_blur
sim/private/controls/cube/kill_rtt
sim/private/controls/cube/lod_bias_forest
sim/private/controls/cube/lod_bias_objects
sim/private/controls/cube/max_dsf_dist
sim/private/controls/cube/recalc_degs_cos
sim/private/controls/debug/debug_line_width
sim/private/controls/debug/debug_point_size
sim/private/controls/debug/debug_text_distance
sim/private/controls/debug/kill_debug_lines
sim/private/controls/debug/show_manipulator_axis
sim/private/controls/debug/show_physics_aircraft
sim/private/controls/debug/texture_browser/keep_textures_alive
sim/private/controls/depth/test_reverse_z_mac
sim/private/controls/disc/-manual disc: auto-set
sim/private/controls/disc/-manual disc: use
sim/private/controls/disc/alpha 01
sim/private/controls/disc/alpha 02
sim/private/controls/disc/alpha 03
sim/private/controls/disc/alpha 04
sim/private/controls/disc/alpha 05
sim/private/controls/disc/alpha 06
sim/private/controls/disc/alpha 07
sim/private/controls/disc/alpha 08
sim/private/controls/disc/alpha 09
sim/private/controls/disc/alpha 10
sim/private/controls/disc/alpha 11
sim/private/controls/disc/alpha 12
sim/private/controls/disc/alpha 13
sim/private/controls/disc/size 01
sim/private/controls/disc/size 02
sim/private/controls/disc/size 03
sim/private/controls/disc/size 04
sim/private/controls/disc/size 05
sim/private/controls/disc/size 06
sim/private/controls/disc/size 07
sim/private/controls/disc/size 08
sim/private/controls/disc/size 09
sim/private/controls/disc/size 10
sim/private/controls/disc/size 11
sim/private/controls/disc/size 12
sim/private/controls/disc/size 13
sim/private/controls/dome/kill_glares
sim/private/controls/dome/sun_gain_1_hdr
sim/private/controls/dome/sun_gain_1_ldr
sim/private/controls/dome/sun_gain_2_hdr
sim/private/controls/dome/sun_gain_2_ldr
sim/private/controls/dome/sun_gain_3_hdr
sim/private/controls/dome/sun_gain_3_ldr
sim/private/controls/dome/sun_glare_dist_dome_rat
sim/private/controls/drape/lock_mesh_n
sim/private/controls/drape/lock_mesh_st
sim/private/controls/drape/lock_mesh_v
sim/private/controls/dsf/always_use_autogen
sim/private/controls/dsf/base_terrain_in_vram
sim/private/controls/dsf/debug_depth
sim/private/controls/dsf/log_ter_load
sim/private/controls/dsf/max_obj_y_err
sim/private/controls/dsf/max_y_tries
sim/private/controls/dsf/normal_rescale
sim/private/controls/dsf/sea_floor
sim/private/controls/dsf/upside_down_tri_cos
sim/private/controls/dsf/use_dem
sim/private/controls/facades/kill_facs
sim/private/controls/facades/maximum_mitre_angle
sim/private/controls/fbo/planet_cam_size
sim/private/controls/fbo/shadow_cam_size
sim/private/controls/fog/fog_be_gone
sim/private/controls/fog/std_deviation_cutoff
sim/private/controls/forest/inn_ring_density
sim/private/controls/forest/inn_ring_lod
sim/private/controls/forest/instance_quads
sim/private/controls/forest/mid_ring_density
sim/private/controls/forest/mid_ring_lod
sim/private/controls/forest/out_ring_density
sim/private/controls/forest/out_ring_lod
sim/private/controls/forest/use_instance
sim/private/controls/geoid/extended_dsfs
sim/private/controls/geoid/force_space_dsfs
sim/private/controls/geoid/override_vis_limit
sim/private/controls/gfx/managed_buffers/max_movement_bytes
sim/private/controls/gfx/managed_buffers/max_movement_count
sim/private/controls/gfx/ogl/use_spirv
sim/private/controls/hdr/attenuation_scale
sim/private/controls/hdr/blur_exp
sim/private/controls/hdr/debug_lights
sim/private/controls/hdr/eye_adjust_cutoff
sim/private/controls/hdr/eye_adjust_time
sim/private/controls/hdr/fsaa_ratio_x
sim/private/controls/hdr/fsaa_ratio_y
sim/private/controls/hdr/gain_max
sim/private/controls/hdr/gain_min
sim/private/controls/hdr/sky_gain
sim/private/controls/hdr/use_post_aa
sim/private/controls/hdr/use_reverse_z
sim/private/controls/hdr/white_point
sim/private/controls/heat/normal_blur
sim/private/controls/heat/telephoto
sim/private/controls/heat/zoom_blur
sim/private/controls/hid/debug/joys
sim/private/controls/instance/instance_grid
sim/private/controls/instance/kill_immediate_stream_obj
sim/private/controls/instance/kill_instance
sim/private/controls/instance/kill_instanced_stream_obj
sim/private/controls/instance/kill_queue_instanced
sim/private/controls/instance/kill_queue_lights
sim/private/controls/instance/max_lod_ratio
sim/private/controls/instance/max_radius_ratio
sim/private/controls/instance/merge_vbos
sim/private/controls/instance/min_count_for_vbo
sim/private/controls/instance/tiny_obj_cutoff
sim/private/controls/instruments/camera_night_cutoff
sim/private/controls/instruments/full_camera
sim/private/controls/light/random_percent
sim/private/controls/lighting/cockpit_lit_bias
sim/private/controls/lighting/deferred_uses_stencil
sim/private/controls/lightning/strike_plane
sim/private/controls/lights/3d/constant_atten
sim/private/controls/lights/3d/rheo_size_curve
sim/private/controls/lights/always_night_lights
sim/private/controls/lights/beacon_rotate_billboard
sim/private/controls/lights/beacon_rotate_spill
sim/private/controls/lights/beacon_strobe_billboard
sim/private/controls/lights/beacon_strobe_spill
sim/private/controls/lights/bloom_far
sim/private/controls/lights/bloom_for_zoom
sim/private/controls/lights/bloom_near
sim/private/controls/lights/dist_far
sim/private/controls/lights/dist_near
sim/private/controls/lights/exponent_far
sim/private/controls/lights/exponent_near
sim/private/controls/lights/fat_omni_cutoff
sim/private/controls/lights/hdr_mix
sim/private/controls/lights/kill_dynamic_billboards
sim/private/controls/lights/kill_dynamic_spill
sim/private/controls/lights/lod_max_static_bb
sim/private/controls/lights/lod_max_static_gnd
sim/private/controls/lights/lod_max_static_sp
sim/private/controls/lights/mix_big
sim/private/controls/lights/mix_small
sim/private/controls/lights/mix_weather_fog
sim/private/controls/lights/mix_weather_rain
sim/private/controls/lights/no_light_groups
sim/private/controls/lights/scale_far
sim/private/controls/lights/scale_near
sim/private/controls/lights/spill_scale
sim/private/controls/lights/srgb_fog_curve
sim/private/controls/lights/vasi_papi_red_b
sim/private/controls/lights/vasi_papi_red_g
sim/private/controls/lights/vasi_papi_red_r
sim/private/controls/lights/vasi_papi_white_b
sim/private/controls/lights/vasi_papi_white_g
sim/private/controls/lights/vasi_papi_white_r
sim/private/controls/manipulators/click_delay
sim/private/controls/map/acf_power
sim/private/controls/map/acf_size
sim/private/controls/map/apt_cross_end
sim/private/controls/map/apt_cross_start
sim/private/controls/map/fix_max_size_m
sim/private/controls/map/nav_max_size_m
sim/private/controls/menus/close_menu_delay_seconds
sim/private/controls/moon/gain_hdr
sim/private/controls/moon/gain_ldr
sim/private/controls/moon/glow_hdr
sim/private/controls/moon/glow_ldr
sim/private/controls/nightvision/gain
sim/private/controls/nightvision/static_alpha
sim/private/controls/obj/show_drag_lines
sim/private/controls/panel/always_render
sim/private/controls/park/static_plane_build_dis
sim/private/controls/park/static_plane_density
sim/private/controls/particle/jitter_hz
sim/private/controls/particle/old_emit_model
sim/private/controls/particle/preview_level
sim/private/controls/particle/preview_radius
sim/private/controls/particle/preview_rpm
sim/private/controls/particle_system/debug_mode
sim/private/controls/perf/cockpit_kill_dist
sim/private/controls/perf/disable_cockpit_readback
sim/private/controls/perf/disable_reflection_cam
sim/private/controls/perf/disable_shadow_prep
sim/private/controls/perf/kill_atc
sim/private/controls/perf/kill_chains
sim/private/controls/perf/kill_click_3d
sim/private/controls/perf/kill_clip
sim/private/controls/perf/kill_cockpit_objects
sim/private/controls/perf/kill_counters
sim/private/controls/perf/kill_cull
sim/private/controls/perf/kill_draped_hard_tris
sim/private/controls/perf/kill_fm
sim/private/controls/perf/kill_gbuf_sun
sim/private/controls/perf/kill_hdr_tone_blit
sim/private/controls/perf/kill_instruments
sim/private/controls/perf/kill_junctions
sim/private/controls/perf/kill_moon
sim/private/controls/perf/kill_panel_bkgnd
sim/private/controls/perf/kill_planes
sim/private/controls/perf/kill_prefill
sim/private/controls/perf/kill_udp_read
sim/private/controls/perf/kill_with_cull_face
sim/private/controls/perf/test_prefill
sim/private/controls/perf/use_hw_stereo
sim/private/controls/perf/use_stereo_cube
sim/private/controls/perf/use_stereo_shadow
sim/private/controls/planes/cull_small_pix
sim/private/controls/planet/ambience_gain
sim/private/controls/planet/ambience_offset
sim/private/controls/planet/ambience_tint
sim/private/controls/planet/exposure
sim/private/controls/planet/kill_hi
sim/private/controls/planet/kill_lo
sim/private/controls/planet/k_depth
sim/private/controls/planet/land_inscatter
sim/private/controls/planet/occlude_factor
sim/private/controls/planet/od_tex_size_x
sim/private/controls/planet/od_tex_size_y
sim/private/controls/planet/r_blue
sim/private/controls/planet/r_depth
sim/private/controls/planet/r_green
sim/private/controls/planet/r_red
sim/private/controls/planet/sky_inscatter
sim/private/controls/planet/want_true_depth
sim/private/controls/planet/wire_frame
sim/private/controls/powerlines/fade_distance
sim/private/controls/preview/acf_psi
sim/private/controls/preview/acf_rad_hi
sim/private/controls/preview/acf_rad_lo
sim/private/controls/preview/acf_the_hi
sim/private/controls/preview/acf_the_lo
sim/private/controls/preview/fov
sim/private/controls/preview/light_amb
sim/private/controls/preview/light_dir
sim/private/controls/preview/lite_the
sim/private/controls/prop/alpha_hi
sim/private/controls/prop/alpha_lo
sim/private/controls/prop/disc_rot_hi
sim/private/controls/prop/disc_rot_lo
sim/private/controls/prop/disc_rot_md
sim/private/controls/prop/tacrad_for_alpha_hi
sim/private/controls/prop/tacrad_for_alpha_lo
sim/private/controls/prop/tacrad_for_rot_hi
sim/private/controls/prop/tacrad_for_rot_lo
sim/private/controls/prop/tacrad_for_rot_md
sim/private/controls/puff/kill_afterburner
sim/private/controls/puff/kill_comp
sim/private/controls/puff/kill_draw
sim/private/controls/puff/kill_make
sim/private/controls/puff/terrain_dust_ratio
sim/private/controls/puff/terrain_spray_ratio
sim/private/controls/rain/kill_3d_rain
sim/private/controls/region/async_per_frame
sim/private/controls/render/cube_prep_mode
sim/private/controls/reno/aniso_filter
sim/private/controls/reno/comp_texes
sim/private/controls/reno/default_view
sim/private/controls/reno/diff_FOV
sim/private/controls/reno/draw_aurora
sim/private/controls/reno/draw_boats
sim/private/controls/reno/draw_cars_05
sim/private/controls/reno/draw_deer_birds
sim/private/controls/reno/draw_detail_apt_03
sim/private/controls/reno/draw_fft_water
sim/private/controls/reno/draw_fire_ball
sim/private/controls/reno/draw_for_05
sim/private/controls/reno/draw_gload
sim/private/controls/reno/draw_HDR
sim/private/controls/reno/draw_objs_06
sim/private/controls/reno/draw_per_pix_liting
sim/private/controls/reno/draw_planet
sim/private/controls/reno/draw_reflect_water05
sim/private/controls/reno/draw_scattering
sim/private/controls/reno/draw_vecs_03
sim/private/controls/reno/draw_view_ind
sim/private/controls/reno/draw_volume_fog01
sim/private/controls/reno/draw_water3d
sim/private/controls/reno/LOD_bias_rat
sim/private/controls/reno/sloped_runways
sim/private/controls/reno/use_bump_maps
sim/private/controls/reno/use_detail_textures
sim/private/controls/reno/view_control
sim/private/controls/road/bridge_minimum
sim/private/controls/road/bury_draped
sim/private/controls/road/check_over_under
sim/private/controls/road/do_pencil
sim/private/controls/road/do_slash
sim/private/controls/road/drape_level_space
sim/private/controls/road/extra_for_straightening
sim/private/controls/road/grade_minimum
sim/private/controls/road/max_default_shear
sim/private/controls/road/max_smooth_depth
sim/private/controls/road/max_smooth_err
sim/private/controls/road/max_uv_distort
sim/private/controls/road/min_smooth_len
sim/private/controls/road/no_composites
sim/private/controls/road/no_plug
sim/private/controls/road/over_under_slop
sim/private/controls/road/powerline_base_extra
sim/private/controls/road/powerline_base_max
sim/private/controls/road/powerline_base_width
sim/private/controls/road/powerline_buffer_dist
sim/private/controls/road/powerline_h_slop
sim/private/controls/road/powerline_interval_flat
sim/private/controls/road/powerline_interval_steep
sim/private/controls/road/powerline_v_slop
sim/private/controls/road/pull_factor
sim/private/controls/road/slash_angle
sim/private/controls/road/smooth_cutoff
sim/private/controls/road/smooth_weight
sim/private/controls/road/start_uv_off
sim/private/controls/road/subdivide_angle
sim/private/controls/road/test_real_types
sim/private/controls/roads/bezier_calc_split_len
sim/private/controls/roads/limit_strip
sim/private/controls/roads/minimum_stacking
sim/private/controls/roads/min_dot_for_mitre
sim/private/controls/roads/noise_freq
sim/private/controls/roads/sink_draped_junctions
sim/private/controls/runloop/tasks_per_frame
sim/private/controls/runloop/time_per_frame_usec
sim/private/controls/runway/blastpad_scale_s
sim/private/controls/runway/blastpad_scale_t
sim/private/controls/runways/kill_snow_effects
sim/private/controls/sh/debug
sim/private/controls/sh/kill_below_horizon
sim/private/controls/sh/sample_count
sim/private/controls/shader/bypass_optimizer
sim/private/controls/shader/tile_default_noise_x
sim/private/controls/shader/tile_default_noise_y
sim/private/controls/shaders/faded_lod
sim/private/controls/shadow/adhoc/extra_far
sim/private/controls/shadow/bias_const
sim/private/controls/shadow/bias_n_constant
sim/private/controls/shadow/bias_n_slope
sim/private/controls/shadow/bias_slope
sim/private/controls/shadow/cockpit_near_adjust
sim/private/controls/shadow/cockpit_near_proxy
sim/private/controls/shadow/csm/far_limit_exterior
sim/private/controls/shadow/csm/far_limit_interior
sim/private/controls/shadow/csm/lambda
sim/private/controls/shadow/csm/near_limit_exterior
sim/private/controls/shadow/csm/near_limit_interior
sim/private/controls/shadow/csm/pad_near_const
sim/private/controls/shadow/csm/pad_near_ratio
sim/private/controls/shadow/csm/print_splits
sim/private/controls/shadow/csm_split_exterior
sim/private/controls/shadow/csm_split_interior
sim/private/controls/shadow/debug_using_color
sim/private/controls/shadow/extra_near
sim/private/controls/shadow/first_3d_pass
sim/private/controls/shadow/lod_bias_adjust
sim/private/controls/shadow/overlap_ratio
sim/private/controls/shadow/scenery_shadows
sim/private/controls/shadow/total_fade_ratio
sim/private/controls/skyc/ambient_ratio_clean
sim/private/controls/skyc/ambient_ratio_foggy
sim/private/controls/skyc/ambient_ratio_hazy
sim/private/controls/skyc/ambient_ratio_hialt
sim/private/controls/skyc/ambient_ratio_mount
sim/private/controls/skyc/ambient_ratio_ocast
sim/private/controls/skyc/ambient_ratio_orbit
sim/private/controls/skyc/ambient_ratio_snowy
sim/private/controls/skyc/ambient_ratio_sockd
sim/private/controls/skyc/ambient_ratio_strat
sim/private/controls/skyc/cld_imm_max
sim/private/controls/skyc/cld_imm_min
sim/private/controls/skyc/darken_tops_for_fog
sim/private/controls/skyc/direct_ratio_clean
sim/private/controls/skyc/direct_ratio_foggy
sim/private/controls/skyc/direct_ratio_hazy
sim/private/controls/skyc/direct_ratio_hialt
sim/private/controls/skyc/direct_ratio_mount
sim/private/controls/skyc/direct_ratio_ocast
sim/private/controls/skyc/direct_ratio_orbit
sim/private/controls/skyc/direct_ratio_snowy
sim/private/controls/skyc/direct_ratio_sockd
sim/private/controls/skyc/direct_ratio_strat
sim/private/controls/skyc/dsf_cutover_scale
sim/private/controls/skyc/dsf_fade_ratio
sim/private/controls/skyc/fog_start_hi_alt
sim/private/controls/skyc/fog_start_lo_alt
sim/private/controls/skyc/gnd_imm_max
sim/private/controls/skyc/gnd_imm_min
sim/private/controls/skyc/lit_imm_max
sim/private/controls/skyc/lit_imm_min
sim/private/controls/skyc/max_dsf_vis_ever
sim/private/controls/skyc/max_shadow_angle
sim/private/controls/skyc/max_tone_angle
sim/private/controls/skyc/mie_scattering_clean
sim/private/controls/skyc/mie_scattering_foggy
sim/private/controls/skyc/mie_scattering_hazy
sim/private/controls/skyc/mie_scattering_hialt
sim/private/controls/skyc/mie_scattering_mount
sim/private/controls/skyc/mie_scattering_ocast
sim/private/controls/skyc/mie_scattering_orbit
sim/private/controls/skyc/mie_scattering_snowy
sim/private/controls/skyc/mie_scattering_sockd
sim/private/controls/skyc/mie_scattering_strat
sim/private/controls/skyc/min_dsf_vis_ever
sim/private/controls/skyc/min_shadow_angle
sim/private/controls/skyc/min_tone_angle
sim/private/controls/skyc/near_clip_maximum
sim/private/controls/skyc/near_clip_minimum
sim/private/controls/skyc/near_clip_zoom_ratio
sim/private/controls/skyc/plugin_forced_near_clip
sim/private/controls/skyc/raleigh_scattering_clean
sim/private/controls/skyc/raleigh_scattering_foggy
sim/private/controls/skyc/raleigh_scattering_hazy
sim/private/controls/skyc/raleigh_scattering_hialt
sim/private/controls/skyc/raleigh_scattering_mount
sim/private/controls/skyc/raleigh_scattering_ocast
sim/private/controls/skyc/raleigh_scattering_orbit
sim/private/controls/skyc/raleigh_scattering_snowy
sim/private/controls/skyc/raleigh_scattering_sockd
sim/private/controls/skyc/raleigh_scattering_strat
sim/private/controls/skyc/scale_light_2d
sim/private/controls/skyc/shadow_level_clean
sim/private/controls/skyc/shadow_level_foggy
sim/private/controls/skyc/shadow_level_hazy
sim/private/controls/skyc/shadow_level_hialt
sim/private/controls/skyc/shadow_level_mount
sim/private/controls/skyc/shadow_level_ocast
sim/private/controls/skyc/shadow_level_orbit
sim/private/controls/skyc/shadow_level_snowy
sim/private/controls/skyc/shadow_level_sockd
sim/private/controls/skyc/shadow_level_strat
sim/private/controls/skyc/shadow_offset_clean
sim/private/controls/skyc/shadow_offset_foggy
sim/private/controls/skyc/shadow_offset_hazy
sim/private/controls/skyc/shadow_offset_hialt
sim/private/controls/skyc/shadow_offset_mount
sim/private/controls/skyc/shadow_offset_ocast
sim/private/controls/skyc/shadow_offset_orbit
sim/private/controls/skyc/shadow_offset_snowy
sim/private/controls/skyc/shadow_offset_sockd
sim/private/controls/skyc/shadow_offset_strat
sim/private/controls/skyc/sky_imm_max
sim/private/controls/skyc/sky_imm_min
sim/private/controls/skyc/sun_angle_aircraft
sim/private/controls/skyc/sun_angle_airport
sim/private/controls/skyc/sun_angle_cars
sim/private/controls/skyc/sun_angle_cockpit
sim/private/controls/skyc/sun_angle_lights
sim/private/controls/skyc/sun_angle_texture
sim/private/controls/skyc/tone_ratio_clean
sim/private/controls/skyc/tone_ratio_foggy
sim/private/controls/skyc/tone_ratio_hazy
sim/private/controls/skyc/tone_ratio_hialt
sim/private/controls/skyc/tone_ratio_mount
sim/private/controls/skyc/tone_ratio_ocast
sim/private/controls/skyc/tone_ratio_orbit
sim/private/controls/skyc/tone_ratio_snowy
sim/private/controls/skyc/tone_ratio_sockd
sim/private/controls/skyc/tone_ratio_strat
sim/private/controls/skyc/white_out_in_clouds
sim/private/controls/sound/debug/spaces
sim/private/controls/sound/debug/trace_volumes
sim/private/controls/ssao/enable
sim/private/controls/ssao/scale
sim/private/controls/stars/gain_hdr
sim/private/controls/stars/gain_ldr
sim/private/controls/stencil/debug_key
sim/private/controls/stencil/debug_mask
sim/private/controls/taxi_signs/inset_divider
sim/private/controls/terrain/car_lod_boost
sim/private/controls/terrain/composite_far_dist_bias
sim/private/controls/terrain/fade_start_rat
sim/private/controls/terrain/far_clip_lim
sim/private/controls/terrain/fog_clip_pad
sim/private/controls/terrain/fog_clip_scale
sim/private/controls/terrain/kill_cars
sim/private/controls/terrain/kill_patches
sim/private/controls/terrain/minimum_zoomed_FOV
sim/private/controls/terrain/min_clip
sim/private/controls/terrain/patch_grid
sim/private/controls/terrain/skip_lod_cull
sim/private/controls/terrain/skip_lod_cull_cluster
sim/private/controls/terrain/skip_sphere_cull
sim/private/controls/terrain/skip_sphere_cull_cluster
sim/private/controls/tess/scale
sim/private/controls/test/capture_offscreen
sim/private/controls/tex/distance_pad
sim/private/controls/tex/ortho_boost_factor
sim/private/controls/tex/paging/downscale_cooldown
sim/private/controls/tex/paging/max_distance
sim/private/controls/tex/paging/max_overdrive
sim/private/controls/tex/preload_dist
sim/private/controls/textures/good_minify
sim/private/controls/texture_browser/alpha_grid_size
sim/private/controls/time/wait_workers
sim/private/controls/translate/debug_hard_coded_strings
sim/private/controls/trucks/any_service_time
sim/private/controls/trucks/crew_service_time
sim/private/controls/vbo_stream/use_mbr
sim/private/controls/vr/debug/reload_manips
sim/private/controls/vr/debug/show_hotspots
sim/private/controls/vr/debug/show_virgin_manips
sim/private/controls/vr/debug/x1
sim/private/controls/vr/debug/x2
sim/private/controls/vr/debug/y1
sim/private/controls/vr/debug/y2
sim/private/controls/vr/mouse/max_z
sim/private/controls/vr/mouse_menu_fwd
sim/private/controls/vr/mouse_size
sim/private/controls/vr/mouse_z_off_draw
sim/private/controls/vr/mouse_z_off_test
sim/private/controls/vr/self_hotspot_angle
sim/private/controls/vr/sitting_is_fwd
sim/private/controls/vr/tchochke/aabb_slop_touch
sim/private/controls/vr/teleport_tune_rate
sim/private/controls/vr/thumbstick_nullzone
sim/private/controls/vr/use_interleave
sim/private/controls/vr/use_post_present
sim/private/controls/vr/z_test
sim/private/controls/water/clip_plane_adjust
sim/private/controls/water/color_end
sim/private/controls/water/color_start
sim/private/controls/water/deep1_b
sim/private/controls/water/deep1_g
sim/private/controls/water/deep1_r
sim/private/controls/water/deep2_b
sim/private/controls/water/deep2_g
sim/private/controls/water/deep2_r
sim/private/controls/water/extra_fov_rat_semi
sim/private/controls/water/fft_amp1
sim/private/controls/water/fft_amp2
sim/private/controls/water/fft_amp3
sim/private/controls/water/fft_amp4
sim/private/controls/water/fft_scale1
sim/private/controls/water/fft_scale2
sim/private/controls/water/fft_scale3
sim/private/controls/water/fft_scale4
sim/private/controls/water/hack_edit
sim/private/controls/water/hack_speed
sim/private/controls/water/land_bias
sim/private/controls/water/noise_amp
sim/private/controls/water/noise_bias_gen_x
sim/private/controls/water/noise_bias_gen_y
sim/private/controls/water/noise_dir
sim/private/controls/water/noise_speed
sim/private/controls/water/perlin_wave1_amp
sim/private/controls/water/perlin_wave1_hdg
sim/private/controls/water/perlin_wave1_rat
sim/private/controls/water/perlin_wave2_amp
sim/private/controls/water/perlin_wave2_hdg
sim/private/controls/water/perlin_wave2_rat
sim/private/controls/water/perlin_wave3_amp
sim/private/controls/water/perlin_wave3_hdg
sim/private/controls/water/perlin_wave3_rat
sim/private/controls/water/perlin_wave4_amp
sim/private/controls/water/perlin_wave4_hdg
sim/private/controls/water/perlin_wave4_rat
sim/private/controls/water/proj_x_dim
sim/private/controls/water/proj_y_dim
sim/private/controls/water/tess_bucket_bias
sim/private/controls/water/wave_ratio
sim/private/controls/wingpuffs/puff_alph_rat
sim/private/controls/wingpuffs/puff_hi_x_rat
sim/private/controls/wingpuffs/puff_hi_y_rat
sim/private/controls/wingpuffs/puff_hi_z_rat
sim/private/controls/wingpuffs/puff_lo_x_rat
sim/private/controls/wingpuffs/puff_lo_y_rat
sim/private/controls/wingpuffs/puff_lo_z_rat
sim/private/controls/wingpuffs/puff_numb_rat
sim/private/controls/wingpuffs/puff_size_rat
sim/private/controls/xdl/always_use_vram
sim/private/controls/yter/default_dsf_surface_is_asphalt
sim/private/controls/yter/y_probe_error_margin
sim/private/remote/cmd_port
sim/private/stats/ag/num_tiles
sim/private/stats/ag/num_trees
sim/private/stats/alloc/static/ibo/count
sim/private/stats/alloc/static/ibo/size_bytes
sim/private/stats/alloc/static/ubo/count
sim/private/stats/alloc/static/ubo/size_bytes
sim/private/stats/alloc/static/vbo/count
sim/private/stats/alloc/static/vbo/size_bytes
sim/private/stats/alloc/streaming/ibo/count
sim/private/stats/alloc/streaming/ibo/size_bytes
sim/private/stats/alloc/streaming/ubo/count
sim/private/stats/alloc/streaming/ubo/size_bytes
sim/private/stats/alloc/streaming/vbo/count
sim/private/stats/alloc/streaming/vbo/size_bytes
sim/private/stats/atc/debug/landing_check_in_progress
sim/private/stats/atc/debug/spawner/total_arr
sim/private/stats/atc/debug/spawner/total_dep
sim/private/stats/atc/debug/spawner/total_enr
sim/private/stats/atc/debug/takeoff_check_in_progress
sim/private/stats/atc/pattern
sim/private/stats/bird/num_draw
sim/private/stats/cars/dead_end
sim/private/stats/cars/out_of_bounds
sim/private/stats/cars/rebucket_cache_hit
sim/private/stats/cars/rebucket_cache_miss
sim/private/stats/clouds/buckets_per_frame
sim/private/stats/clouds/puffs_per_frame
sim/private/stats/clouds/slices_per_frame
sim/private/stats/clouds/transforms_per_frame
sim/private/stats/font/tex_mem
sim/private/stats/forests/pass
sim/private/stats/forests/total_trees_ever
sim/private/stats/forests/try
sim/private/stats/gfx/managed_buffers/agp/bytes
sim/private/stats/gfx/managed_buffers/agp/count
sim/private/stats/gfx/managed_buffers/cold/bytes
sim/private/stats/gfx/managed_buffers/cold/count
sim/private/stats/gfx/managed_buffers/count
sim/private/stats/gfx/managed_buffers/device/bytes
sim/private/stats/gfx/managed_buffers/device/count
sim/private/stats/gfx/managed_buffers/host/bytes
sim/private/stats/gfx/managed_buffers/host/count
sim/private/stats/gfx/managed_buffers/hot/bytes
sim/private/stats/gfx/managed_buffers/hot/count
sim/private/stats/gfx/managed_buffers/missed/bytes
sim/private/stats/gfx/managed_buffers/missed/count
sim/private/stats/gfx/managed_buffers/paging_arena_bytes
sim/private/stats/gfx/managed_buffers/paging_enabled
sim/private/stats/gfx/managed_buffers/warm/bytes
sim/private/stats/gfx/managed_buffers/warm/count
sim/private/stats/gfx/pipelines/blit/num_pipelines
sim/private/stats/gfx/pipelines/blur/num_pipelines
sim/private/stats/gfx/pipelines/boat_wake/num_pipelines
sim/private/stats/gfx/pipelines/cloud_puffs/num_pipelines
sim/private/stats/gfx/pipelines/cube_filter/num_pipelines
sim/private/stats/gfx/pipelines/debug/num_pipelines
sim/private/stats/gfx/pipelines/deferred/num_pipelines
sim/private/stats/gfx/pipelines/deferred_ssao/num_pipelines
sim/private/stats/gfx/pipelines/dome/num_pipelines
sim/private/stats/gfx/pipelines/font/num_pipelines
sim/private/stats/gfx/pipelines/ground_lights/num_pipelines
sim/private/stats/gfx/pipelines/hdr/num_pipelines
sim/private/stats/gfx/pipelines/legacy_depth/num_pipelines
sim/private/stats/gfx/pipelines/legacy_flat/num_pipelines
sim/private/stats/gfx/pipelines/light/num_pipelines
sim/private/stats/gfx/pipelines/line3d/num_pipelines
sim/private/stats/gfx/pipelines/lit/num_pipelines
sim/private/stats/gfx/pipelines/manip3d/num_pipelines
sim/private/stats/gfx/pipelines/particle/num_pipelines
sim/private/stats/gfx/pipelines/prop_disc/num_pipelines
sim/private/stats/gfx/pipelines/puff/num_pipelines
sim/private/stats/gfx/pipelines/rain/num_pipelines
sim/private/stats/gfx/pipelines/resolve/num_pipelines
sim/private/stats/gfx/pipelines/sectional2/num_pipelines
sim/private/stats/gfx/pipelines/shadow_rect/num_pipelines
sim/private/stats/gfx/pipelines/ssao_blur/num_pipelines
sim/private/stats/gfx/pipelines/terrain/num_pipelines
sim/private/stats/gfx/pipelines/total_jit_pipelines
sim/private/stats/gfx/pipelines/total_pipelines
sim/private/stats/gfx/pipelines/wxr_mask/num_pipelines
sim/private/stats/instance/num_clusters
sim/private/stats/instance/num_cluster_objs
sim/private/stats/lights/3d/atten1
sim/private/stats/lights/3d/atten2
sim/private/stats/lights/3d/atten3
sim/private/stats/lights/dynamic_dir_count
sim/private/stats/lights/dynamic_spill_count
sim/private/stats/lua/total_bytes_alloc
sim/private/stats/lua/total_bytes_alloc_maximum
sim/private/stats/object/num_batces
sim/private/stats/object/num_cluster_batches
sim/private/stats/object/num_cluster_tris
sim/private/stats/object/num_cmds
sim/private/stats/object/num_lines
sim/private/stats/object/num_mouse_tri
sim/private/stats/object/num_objs
sim/private/stats/object/num_objs_change
sim/private/stats/object/num_obj_clusters
sim/private/stats/object/num_obj_cluster_objs
sim/private/stats/object/num_obj_streams
sim/private/stats/object/num_obj_stream_imm
sim/private/stats/object/num_obj_stream_imm_shader
sim/private/stats/object/num_obj_stream_objs
sim/private/stats/object/num_stream_batches
sim/private/stats/object/num_stream_tris
sim/private/stats/object/num_tris
sim/private/stats/object/pln_obj_count
sim/private/stats/ogl/swap_time_total
sim/private/stats/panel/num_insts_drawn
sim/private/stats/panel/read_passes
sim/private/stats/panel/read_pixels
sim/private/stats/particle/editor_math_usec
sim/private/stats/particle/editor_plot_usec
sim/private/stats/planes/plot_per_frame
sim/private/stats/planet/effective_vis
sim/private/stats/planet/num_10x10
sim/private/stats/planet/passes
sim/private/stats/shadow/num_csm_culls
sim/private/stats/shadow/passes_per_frame
sim/private/stats/skyc/ambient_ratio_final
sim/private/stats/skyc/direct_ratio_final
sim/private/stats/skyc/earth/planet_near_clip
sim/private/stats/skyc/fog/far_dis_clip
sim/private/stats/skyc/fog/far_dis_dsf
sim/private/stats/skyc/fog/far_fog_cld
sim/private/stats/skyc/fog/far_fog_lit
sim/private/stats/skyc/fog/far_fog_unlit
sim/private/stats/skyc/fog/near_dis_clip
sim/private/stats/skyc/fog/near_dis_dsf
sim/private/stats/skyc/fog/near_fog_cld
sim/private/stats/skyc/fog/near_fog_lit
sim/private/stats/skyc/fog/near_fog_unlit
sim/private/stats/skyc/imm_rat_cld
sim/private/stats/skyc/imm_rat_gnd
sim/private/stats/skyc/imm_rat_lit
sim/private/stats/skyc/imm_rat_sky
sim/private/stats/skyc/light_atten_hi
sim/private/stats/skyc/light_atten_lo
sim/private/stats/skyc/light_atten_rat
sim/private/stats/skyc/mie_scattering_final
sim/private/stats/skyc/mon_amb_b
sim/private/stats/skyc/mon_amb_g
sim/private/stats/skyc/mon_amb_r
sim/private/stats/skyc/mon_dir_b
sim/private/stats/skyc/mon_dir_g
sim/private/stats/skyc/mon_dir_r
sim/private/stats/skyc/raleigh_scattering_final
sim/private/stats/skyc/shadow_level_final
sim/private/stats/skyc/shadow_offset_final
sim/private/stats/skyc/sun_amb_b
sim/private/stats/skyc/sun_amb_g
sim/private/stats/skyc/sun_amb_r
sim/private/stats/skyc/sun_dir_b
sim/private/stats/skyc/sun_dir_g
sim/private/stats/skyc/sun_dir_r
sim/private/stats/skyc/tone_ratio_final
sim/private/stats/skyc/vis/haze_scale
sim/private/stats/skyc/vis/tone_map
sim/private/stats/skyc/vis/tone_scale
sim/private/stats/skyc/vis/view_sigma
sim/private/stats/terrain/LOD_bias_final
sim/private/stats/terrain/num_car_buckets
sim/private/stats/terrain/num_car_drape
sim/private/stats/terrain/num_car_lights
sim/private/stats/terrain/num_car_shadows
sim/private/stats/terrain/num_car_test
sim/private/stats/terrain/num_cluster_bucket
sim/private/stats/terrain/num_cluster_draw
sim/private/stats/terrain/num_cluster_obj
sim/private/stats/terrain/num_cluster_test
sim/private/stats/terrain/num_layers
sim/private/stats/terrain/num_object_buckets
sim/private/stats/terrain/num_object_draw
sim/private/stats/terrain/num_object_shadows
sim/private/stats/terrain/num_object_test
sim/private/stats/terrain/num_patch_bucket
sim/private/stats/terrain/num_patch_draw
sim/private/stats/terrain/num_patch_shadows
sim/private/stats/terrain/num_patch_test
sim/private/stats/terrain/num_vis_buckets
sim/private/stats/terrain/num_water_buckets
sim/private/stats/terrain/num_water_draw
sim/private/stats/terrain/num_water_test
sim/private/stats/test/mempool/arena
sim/private/stats/test/mempool/available
sim/private/stats/test/mempool/wasted
sim/private/stats/test/mempool/wasted_large
sim/private/stats/time/thread_sync_wait
sim/private/stats/ubo/caches/material
sim/private/stats/ubo/caches/projection
sim/private/stats/ubo/num_write/environment
sim/private/stats/ubo/num_write/light_data
sim/private/stats/ubo/num_write/material_no_cache
sim/private/stats/ubo/num_write/misc
sim/private/stats/ubo/num_write/projection
sim/private/stats/ubo/num_write/projection_no_cache
sim/private/stats/ubo/num_write/shadow
sim/private/stats/ubo/num_write/water
sim/private/stats/water/msl
sim/private/stats/xdl/num_xdl_draw
sim/private/stats/xdl/num_xdl_inst
sim/private/stats/xdl/num_xdl_vert
iphone/flightmodel/ground_status
iphone/indicators/descent_angle_deg
)""";

std::vector<std::string> getInternalList() {

    std::vector<std::string> lines;
    boost::split(lines, raw_list, boost::is_any_of("\n"));

    return lines;
}
